// Code generated by "dataclass -type ScannedItem -field Line string,Item Item -output index_dataclass_scanneditem_generated.go"; DO NOT EDIT.

package joiner

type ScannedItem interface {
	Line() string
	Item() Item
}
type scannedItem struct {
	line string
	item Item
}

func (s *scannedItem) Line() string { return s.line }
func (s *scannedItem) Item() Item   { return s.item }
func NewScannedItem(
	line string,
	item Item,
) ScannedItem {
	return &scannedItem{
		line: line,
		item: item,
	}
}
