// Code generated by "marker -method IsNode -type Location,Relation,JoinKey -output ast_marker_generated.go"; DO NOT EDIT.

package joinkey

func (*Location) IsNode() {}
func (*Relation) IsNode() {}
func (*JoinKey) IsNode()  {}
